version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/Acrolinx.Net.Demo/"
    schedule:
      interval: "daily"
