language: csharp
solution: Acrolinx.Net.Demo.sln
mono: none
dotnet: 3.0.100
before_script:
 - dotnet restore
script:
 - dotnet build
after_success:
 - Acrolinx.Net.Demo\bin\Debug\netcoreapp3.0\Acrolinx.Net.Demo -s | grep "Acrolinx Scorecard: https://test-ssl.acrolinx.com"