language: csharp
solution: Acrolinx.Net.Demo.sln
mono: none
dotnet: 3.0.100
install:
 - dotnet restore
script:
 - dotnet build
after_success:
 - ls -s
 - ./Acrolinx.Net.Demo/bin/Debug/netcoreapp3.0/Acrolinx.Net.Demo -silent
 - "./Acrolinx.Net.Demo/bin/Debug/netcoreapp3.0/Acrolinx.Net.Demo -silent | grep 'Acrolinx Scorecard: https://test-ssl.acrolinx.com'"